extends Node
## Global signal bus (spec §2.3). Systems communicate through these signals
## instead of hard node references, which keeps layers decoupled and makes the
## eventual multiplayer refactor far easier. Emitted from other scripts, so the
## autoload's own parser flags them "unused" — suppress that noise per-signal.

@warning_ignore("unused_signal")
signal ball_banked(team: String)
@warning_ignore("unused_signal")
signal pass_thrown(ball: Node, receiver: Node)
@warning_ignore("unused_signal")
signal ball_state_changed(ball: Node)
@warning_ignore("unused_signal")
signal actor_tagged(actor: Node)
@warning_ignore("unused_signal")
signal match_won(team: String)
@warning_ignore("unused_signal")
signal match_started(user_team: String, cam_mode: String)
@warning_ignore("unused_signal")
@warning_ignore("unused_signal")
signal match_restart()
@warning_ignore("unused_signal")
signal returned_to_menu()
@warning_ignore("unused_signal")
signal open_settings_request()
@warning_ignore("unused_signal")
signal settings_closed_standalone()
@warning_ignore("unused_signal")
signal settings_applied()
@warning_ignore("unused_signal")
signal game_paused(paused: bool)
@warning_ignore("unused_signal")
signal item_grabbed(actor: Node, item: Node)
@warning_ignore("unused_signal")
signal pass_caught(actor: Node)
@warning_ignore("unused_signal")
signal pass_intercepted(actor: Node)
@warning_ignore("unused_signal")
signal countdown_tick(n: int)
